-- =============================================================================
-- 003 · Ubicaciones: departamentos (18) y municipios (298) de Honduras
-- -----------------------------------------------------------------------------
-- El municipio es la "ciudad" de las URLs: /categoria/panaderias/san-pedro-sula
-- Usar un catálogo (y no texto libre) evita que "SPS", "San Pedro" y
-- "San Pedro Sula" generen páginas distintas y dispersen el SEO.
--
-- · Slug único a nivel nacional. Si el nombre se repite en varios
--   departamentos se agrega el departamento: san-jose-copan, san-jose-la-paz.
-- · Distrito Central se muestra como "Tegucigalpa" (así se busca en Google);
--   Comayagüela va en el campo "localidad" del negocio.
-- · destacado = ciudades principales (inicio y primeras opciones del selector).
-- Datos: división político-administrativa vigente (298 municipios).
-- Requiere: 001, 002
-- =============================================================================

create table if not exists public.departamentos (
  id     smallint primary key,
  nombre text not null unique,
  slug   text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

create table if not exists public.municipios (
  id              smallint generated by default as identity primary key,
  departamento_id smallint not null references public.departamentos (id) on delete restrict,
  nombre          text not null,
  slug            text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  destacado       boolean not null default false,
  unique (departamento_id, nombre)
);

create index if not exists municipios_departamento_idx on public.municipios (departamento_id);

comment on table public.municipios is 'Catálogo de municipios. Es la "ciudad" usada en URLs y filtros.';

-- -----------------------------------------------------------------------------
-- Seed: departamentos (código oficial del departamento como id)
-- -----------------------------------------------------------------------------
insert into public.departamentos (id, nombre, slug) values
  (1,  'Atlántida',          'atlantida'),
  (2,  'Colón',              'colon'),
  (3,  'Comayagua',          'comayagua'),
  (4,  'Copán',              'copan'),
  (5,  'Cortés',             'cortes'),
  (6,  'Choluteca',          'choluteca'),
  (7,  'El Paraíso',         'el-paraiso'),
  (8,  'Francisco Morazán',  'francisco-morazan'),
  (9,  'Gracias a Dios',     'gracias-a-dios'),
  (10, 'Intibucá',           'intibuca'),
  (11, 'Islas de la Bahía',  'islas-de-la-bahia'),
  (12, 'La Paz',             'la-paz'),
  (13, 'Lempira',            'lempira'),
  (14, 'Ocotepeque',         'ocotepeque'),
  (15, 'Olancho',            'olancho'),
  (16, 'Santa Bárbara',      'santa-barbara'),
  (17, 'Valle',              'valle'),
  (18, 'Yoro',               'yoro')
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- Seed: municipios
-- -----------------------------------------------------------------------------
with datos (departamento_id, nombre, destacado) as (
  values
  -- Atlántida (8)
  (1, 'La Ceiba', true), (1, 'El Porvenir', false), (1, 'Esparta', false), (1, 'Jutiapa', false),
  (1, 'La Masica', false), (1, 'San Francisco', false), (1, 'Tela', true), (1, 'Arizona', false),
  -- Colón (10)
  (2, 'Trujillo', false), (2, 'Balfate', false), (2, 'Iriona', false), (2, 'Limón', false),
  (2, 'Sabá', false), (2, 'Santa Fe', false), (2, 'Santa Rosa de Aguán', false), (2, 'Sonaguera', false),
  (2, 'Tocoa', true), (2, 'Bonito Oriental', false),
  -- Comayagua (21)
  (3, 'Comayagua', true), (3, 'Ajuterique', false), (3, 'El Rosario', false), (3, 'Esquías', false),
  (3, 'Humuya', false), (3, 'La Libertad', false), (3, 'Lamaní', false), (3, 'La Trinidad', false),
  (3, 'Lejamaní', false), (3, 'Meámbar', false), (3, 'Minas de Oro', false), (3, 'Ojos de Agua', false),
  (3, 'San Jerónimo', false), (3, 'San José de Comayagua', false), (3, 'San José del Potrero', false),
  (3, 'San Luis', false), (3, 'San Sebastián', false), (3, 'Siguatepeque', true),
  (3, 'Villa de San Antonio', false), (3, 'Las Lajas', false), (3, 'Taulabé', false),
  -- Copán (23)
  (4, 'Santa Rosa de Copán', true), (4, 'Cabañas', false), (4, 'Concepción', false),
  (4, 'Copán Ruinas', false), (4, 'Corquín', false), (4, 'Cucuyagua', false), (4, 'Dolores', false),
  (4, 'Dulce Nombre', false), (4, 'El Paraíso', false), (4, 'Florida', false), (4, 'La Jigua', false),
  (4, 'La Unión', false), (4, 'Nueva Arcadia', false), (4, 'San Agustín', false), (4, 'San Antonio', false),
  (4, 'San Jerónimo', false), (4, 'San José', false), (4, 'San Juan de Opoa', false),
  (4, 'San Nicolás', false), (4, 'San Pedro', false), (4, 'Santa Rita', false),
  (4, 'Trinidad de Copán', false), (4, 'Veracruz', false),
  -- Cortés (12)
  (5, 'San Pedro Sula', true), (5, 'Choloma', true), (5, 'Omoa', false), (5, 'Pimienta', false),
  (5, 'Potrerillos', false), (5, 'Puerto Cortés', true), (5, 'San Antonio de Cortés', false),
  (5, 'San Francisco de Yojoa', false), (5, 'San Manuel', false), (5, 'Santa Cruz de Yojoa', false),
  (5, 'Villanueva', true), (5, 'La Lima', true),
  -- Choluteca (16)
  (6, 'Choluteca', true), (6, 'Apacilagua', false), (6, 'Concepción de María', false), (6, 'Duyure', false),
  (6, 'El Corpus', false), (6, 'El Triunfo', false), (6, 'Marcovia', false), (6, 'Morolica', false),
  (6, 'Namasigüe', false), (6, 'Orocuina', false), (6, 'Pespire', false),
  (6, 'San Antonio de Flores', false), (6, 'San Isidro', false), (6, 'San José', false),
  (6, 'San Marcos de Colón', false), (6, 'Santa Ana de Yusguare', false),
  -- El Paraíso (19)
  (7, 'Yuscarán', false), (7, 'Alauca', false), (7, 'Danlí', true), (7, 'El Paraíso', false),
  (7, 'Güinope', false), (7, 'Jacaleapa', false), (7, 'Liure', false), (7, 'Morocelí', false),
  (7, 'Oropolí', false), (7, 'Potrerillos', false), (7, 'San Antonio de Flores', false),
  (7, 'San Lucas', false), (7, 'San Matías', false), (7, 'Soledad', false), (7, 'Teupasenti', false),
  (7, 'Texiguat', false), (7, 'Vado Ancho', false), (7, 'Yauyupe', false), (7, 'Trojes', false),
  -- Francisco Morazán (28)
  (8, 'Tegucigalpa', true),  -- municipio del Distrito Central
  (8, 'Alubarén', false), (8, 'Cedros', false), (8, 'Curarén', false), (8, 'El Porvenir', false),
  (8, 'Guaimaca', false), (8, 'La Libertad', false), (8, 'La Venta', false), (8, 'Lepaterique', false),
  (8, 'Maraita', false), (8, 'Marale', false), (8, 'Nueva Armenia', false), (8, 'Ojojona', false),
  (8, 'Orica', false), (8, 'Reitoca', false), (8, 'Sabanagrande', false),
  (8, 'San Antonio de Oriente', false), (8, 'San Buenaventura', false), (8, 'San Ignacio', false),
  (8, 'Cantarranas', false),  -- oficialmente San Juan de Flores
  (8, 'San Miguelito', false), (8, 'Santa Ana', false), (8, 'Santa Lucía', false),
  (8, 'Talanga', false), (8, 'Tatumbla', false), (8, 'Valle de Ángeles', false),
  (8, 'Villa de San Francisco', false), (8, 'Vallecillo', false),
  -- Gracias a Dios (6)
  (9, 'Puerto Lempira', false), (9, 'Brus Laguna', false), (9, 'Ahuas', false),
  (9, 'Juan Francisco Bulnes', false), (9, 'Ramón Villeda Morales', false), (9, 'Wampusirpi', false),
  -- Intibucá (17)
  (10, 'La Esperanza', false), (10, 'Camasca', false), (10, 'Colomoncagua', false), (10, 'Concepción', false),
  (10, 'Dolores', false), (10, 'Intibucá', false), (10, 'Jesús de Otoro', false), (10, 'Magdalena', false),
  (10, 'Masaguara', false), (10, 'San Antonio', false), (10, 'San Isidro', false), (10, 'San Juan', false),
  (10, 'San Marcos de la Sierra', false), (10, 'San Miguel Guancapla', false), (10, 'Santa Lucía', false),
  (10, 'Yamaranguila', false), (10, 'San Francisco de Opalaca', false),
  -- Islas de la Bahía (4)
  (11, 'Roatán', true), (11, 'Guanaja', false), (11, 'José Santos Guardiola', false), (11, 'Utila', false),
  -- La Paz (19)
  (12, 'La Paz', false), (12, 'Aguanqueterique', false), (12, 'Cabañas', false), (12, 'Cane', false),
  (12, 'Chinacla', false), (12, 'Guajiquiro', false), (12, 'Lauterique', false), (12, 'Marcala', false),
  (12, 'Mercedes de Oriente', false), (12, 'Opatoro', false), (12, 'San Antonio del Norte', false),
  (12, 'San José', false), (12, 'San Juan', false), (12, 'San Pedro de Tutule', false),
  (12, 'Santa Ana', false), (12, 'Santa Elena', false), (12, 'Santa María', false),
  (12, 'Santiago de Puringla', false), (12, 'Yarula', false),
  -- Lempira (28)
  (13, 'Gracias', false), (13, 'Belén', false), (13, 'Candelaria', false), (13, 'Cololaca', false),
  (13, 'Erandique', false), (13, 'Gualcince', false), (13, 'Guarita', false), (13, 'La Campa', false),
  (13, 'La Iguala', false), (13, 'Las Flores', false), (13, 'La Unión', false), (13, 'La Virtud', false),
  (13, 'Lepaera', false), (13, 'Mapulaca', false), (13, 'Piraera', false), (13, 'San Andrés', false),
  (13, 'San Francisco', false), (13, 'San Juan Guarita', false), (13, 'San Manuel Colohete', false),
  (13, 'San Rafael', false), (13, 'San Sebastián', false), (13, 'Santa Cruz', false), (13, 'Talgua', false),
  (13, 'Tambla', false), (13, 'Tomalá', false), (13, 'Valladolid', false), (13, 'Virginia', false),
  (13, 'San Marcos de Caiquín', false),
  -- Ocotepeque (16)
  (14, 'Ocotepeque', false), (14, 'Belén Gualcho', false), (14, 'Concepción', false),
  (14, 'Dolores Merendón', false), (14, 'Fraternidad', false), (14, 'La Encarnación', false),
  (14, 'La Labor', false), (14, 'Lucerna', false), (14, 'Mercedes', false), (14, 'San Fernando', false),
  (14, 'San Francisco del Valle', false), (14, 'San Jorge', false), (14, 'San Marcos', false),
  (14, 'Santa Fe', false), (14, 'Sensenti', false), (14, 'Sinuapa', false),
  -- Olancho (23)
  (15, 'Juticalpa', true), (15, 'Campamento', false), (15, 'Catacamas', true), (15, 'Concordia', false),
  (15, 'Dulce Nombre de Culmí', false), (15, 'El Rosario', false), (15, 'Esquipulas del Norte', false),
  (15, 'Gualaco', false), (15, 'Guarizama', false), (15, 'Guata', false), (15, 'Guayape', false),
  (15, 'Jano', false), (15, 'La Unión', false), (15, 'Mangulile', false), (15, 'Manto', false),
  (15, 'Salamá', false), (15, 'San Esteban', false), (15, 'San Francisco de Becerra', false),
  (15, 'San Francisco de la Paz', false), (15, 'Santa María del Real', false), (15, 'Silca', false),
  (15, 'Yocón', false), (15, 'Patuca', false),
  -- Santa Bárbara (28)
  (16, 'Santa Bárbara', false), (16, 'Arada', false), (16, 'Atima', false), (16, 'Azacualpa', false),
  (16, 'Ceguaca', false), (16, 'San José de Colinas', false), (16, 'Concepción del Norte', false),
  (16, 'Concepción del Sur', false), (16, 'Chinda', false), (16, 'El Níspero', false), (16, 'Gualala', false),
  (16, 'Ilama', false), (16, 'Macuelizo', false), (16, 'Naranjito', false), (16, 'Nuevo Celilac', false),
  (16, 'Petoa', false), (16, 'Protección', false), (16, 'Quimistán', false),
  (16, 'San Francisco de Ojuera', false), (16, 'San Luis', false), (16, 'San Marcos', false),
  (16, 'San Nicolás', false), (16, 'San Pedro Zacapa', false), (16, 'Santa Rita', false),
  (16, 'San Vicente Centenario', false), (16, 'Trinidad', false), (16, 'Las Vegas', false),
  (16, 'Nueva Frontera', false),
  -- Valle (9)
  (17, 'Nacaome', false), (17, 'Alianza', false), (17, 'Amapala', false), (17, 'Aramecina', false),
  (17, 'Caridad', false), (17, 'Goascorán', false), (17, 'Langue', false),
  (17, 'San Francisco de Coray', false), (17, 'San Lorenzo', false),
  -- Yoro (11)
  (18, 'Yoro', false), (18, 'Arenal', false), (18, 'El Negrito', false), (18, 'El Progreso', true),
  (18, 'Jocón', false), (18, 'Morazán', false), (18, 'Olanchito', true), (18, 'Santa Rita', false),
  (18, 'Sulaco', false), (18, 'Victoria', false), (18, 'Yorito', false)
),
con_slug as (
  select
    d.departamento_id,
    d.nombre,
    d.destacado,
    public.slugify(d.nombre) as base,
    count(*) over (partition by public.slugify(d.nombre)) as repeticiones
  from datos d
)
insert into public.municipios (departamento_id, nombre, slug, destacado)
select
  c.departamento_id,
  c.nombre,
  -- Nombre repetido en varios departamentos -> se agrega el departamento,
  -- salvo el municipio homónimo de su departamento (El Paraíso, El Paraíso).
  case when c.repeticiones > 1 and c.base <> dep.slug then c.base || '-' || dep.slug else c.base end,
  c.destacado
from con_slug c
join public.departamentos dep on dep.id = c.departamento_id
order by c.departamento_id, c.nombre
on conflict (slug) do nothing;

-- -----------------------------------------------------------------------------
-- RLS: lectura pública, escritura solo admin
-- -----------------------------------------------------------------------------
alter table public.departamentos enable row level security;
alter table public.municipios enable row level security;

drop policy if exists "departamentos: lectura pública" on public.departamentos;
create policy "departamentos: lectura pública"
  on public.departamentos for select to anon, authenticated using (true);

drop policy if exists "municipios: lectura pública" on public.municipios;
create policy "municipios: lectura pública"
  on public.municipios for select to anon, authenticated using (true);

-- Escritura solo admin (una política por operación para no duplicar el SELECT)
drop policy if exists "municipios: admin inserta" on public.municipios;
create policy "municipios: admin inserta"
  on public.municipios for insert to authenticated
  with check ((select public.is_admin()));

drop policy if exists "municipios: admin edita" on public.municipios;
create policy "municipios: admin edita"
  on public.municipios for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "municipios: admin elimina" on public.municipios;
create policy "municipios: admin elimina"
  on public.municipios for delete to authenticated
  using ((select public.is_admin()));

-- departamentos: catálogo fijo, solo lectura desde la app.
revoke insert, update, delete on public.departamentos from anon, authenticated;
revoke insert, update, delete on public.municipios from anon;
grant select on public.departamentos, public.municipios to anon, authenticated;
grant insert, update, delete on public.municipios to authenticated;
